epochs: 150
save_dir: saved/
save_period: 5
verbosity: 2
monitor: min val_loss
early_stop: 100
visualize: wandb
wandb_project: ss_homework
wandb_name: paper_model_batch_acum
wandb_entity: wandb_pirogok
len_epoch: 1500
batch_acum: 5
grad_norm_clip: 10
