epochs: 500
save_dir: saved/
save_period: 5
verbosity: 2
monitor: min val_loss
early_stop: 100
visualize: wandb
wandb_project: ss_homework
wandb_name: model_improve
wandb_entity: wandb_pirogok
len_epoch: 1500
batch_acum: 8
grad_norm_clip: 10
