- type: SISDRMetric
  args:
    name: SI-SDR Metric
    train: true
    zero_mean: false
    comb: false

- type: SISDRMetric
  args:
    name: Comb SI-SDR Metric
    train: true
    zero_mean: false
    comb: true

- type: CEMetric
  args:
    name: CE Metric
    train: true

- type: PESQMetric
  args:
    name: PESQ Metric
    train: false
    fs: 16000
    mode: wb
    n_processes: 8

